# Generated by Django 3.0.3 on 2020-07-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='nutritional_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntype', to='restaurants.NutritionalType'),
        ),
        migrations.AlterField(
            model_name='nutritionalvalues',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionalvalues', to='restaurants.Product'),
        ),
    ]
